# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json

-   repo: https://github.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
    -     id: flake8
    exclude: 'demo.py|env|scikit-prepare.ipynb'

-   repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
    -   id: codespell
        name: codespell
     #   description: Checks for common misspellings in text files.
        entry: codespell --ignore-words ignore-spelling-words.txt readme.md
        language: python
        types: [text]
